### ISSUE TITLE
issues in android beta 4

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#133]
- npc does effects to water but should not make splash sound
- 
![Picsart_22-05-08_18-42-15-258](https://user-images.githubusercontent.com/101902085/167345748-cfd3fc79-658b-4af1-9844-fda59f0aeb43.jpg)
buttons should be like this
![Screenshot_2022-05-07-09-45-40-155_io github doukutsu_rs](https://user-images.githubusercontent.com/101902085/167345812-96cb2797-0bbc-43bc-924f-9e246b7a3cc3.jpg)
-dobble puppy 
https://user-images.githubusercontent.com/101902085/167345891-eb15f991-fdda-4e0f-9e36-c9ac6a9174ab.mp4
-criture jump the open thier fan istead of only jumping

https://user-images.githubusercontent.com/101902085/167345986-c57760f2-a730-4f2d-971a-801a566468af.mp4
-jake box is not responding
also esc button not working while replay challenge

**Comment by Awesomegamer6566** [comment]
> * npc does effects to water but should not make splash sound

Which one(s)?

> * -dobble puppy

Probably just an issue with the challenge. Might be good to look into though.

> * -criture jump the open thier fan istead of only jumping

A little confused on the wording but that's normal. If a critter is next to a wall then it just won't fly.

> * -jake box is not responding

Your gonna have to find a way to record input. I have no idea if your actually doing anything.

> * also esc button not working while replay challenge

If you can confirm that you are running the current version then I will put this issue here: [The issue list](https://github.com/doukutsu-rs/doukutsu-rs/issues/118)

**Comment by dananothername** [comment]
. in the machine gun challenge the bat makes sound all over the second room
. here is jake box not responding or exiting 
with current version 

Uploading Screenrecorder-2022-05-10-11-01-18-31.mp4…

**Comment by dananothername** [comment]
> ``

Uploading Screenrecorder-2022-05-10-11-01-18-31.mp4…

**Comment by Fancy2209** [comment]
> 
> > ``
> 
> Uploading Screenrecorder-2022-05-10-11-01-18-31.mp4…
> 
> 

You need to wait until it changes from Uploading to it to work
