### ISSUE TITLE
a video for coop bugs 

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#151]
https://m.youtube.com/watch?v=gQ4Y5uRhSeM

**Comment by jozsefsallai** [comment]
Instead of making us watch a full-length speedrun of Boss Attack and let us guess what the bugs are, you could've at least added timestamps in your issue that point to where the bug actually happens. At least you provided a list of bugs in the description.

> the second player doesn't have booster equiped or air tank (also he doesn't have menu)

You're playing an old version, this was fixed. Also the second player is not supposed to have a menu.

> iron head room messed up

Again, this was also fixed, you're playing on an old version.

> the game in tas has one frame late

I don't understand + I still don't recommend speedrunning/TASing a game engine that's a work in progress.

> pressing x in menu cancel every thing so i hold z only +i must close it with Q or X

I don't understand this either, please elaborate.

---

On an added note, I really don't recommend sending us bug reports with TAS footage as it's more difficult to see what the bug actually is.
