### ISSUE TITLE
Overflow subtraction crash due to Windows nano timer quirks

### ISSUE THREAD

**Issue by MeguminSama** [doukutsu-rs/doukutsu-rs#3]
When running the latest doukutsu-rs build, opening a context menu in ShareX (possibly other software) causes the game to crash.

Interestingly, it doesn't happen every time, but it happens most times.

The error thrown is `thread 'main' panicked at 'attempt to subtract with overflow', src\lib.rs:134:22`

GIF Demonstration:
![Crash Bug](https://i.imgur.com/SKKxfkH.gif)

**Comment by MeguminSama** [comment]
Seems to occur when alt-tabbing too.

**Comment by alula** [comment]
fix incoming in #8

**Comment by alula** [comment]
It's known that Win32's `QueryPerformanceCounter()` isn't really monotonic and the issue seems to be caused by the fact Windows changes the process priority and sometimes moves it across CPUs (which have different values in their performance counters), causing an integer overflow when `elapsed()` returns a value bigger than one measured and stored at `last_tick` and therefore triggers Rust's overflow checker.
